import { LandRecord, RecentUpload } from "@/types/landRecord";

// NOTE: All names, villages, and identifiers below are fictional placeholder
// data generated for demonstration purposes only. No real land records or
// personal data are used anywhere in this project.

export const landRecords: LandRecord[] = [
  {
    id: "LR-100234",
    ownerName: "Ramesh Chandra Yadav",
    guardianName: "Late Sh. Baldev Yadav",
    village: "Sarai Kale Khan",
    district: "Gautam Buddh Nagar",
    state: "Uttar Pradesh",
    khasraNumber: "412/2",
    khatauniNumber: "1187",
    areaValue: 2.4,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2019-03-11",
    lastUpdated: "2026-08-02",
    documentName: "khasra-412-2-sale-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 2380,
    mutationNumber: "MUT-77213",
    marketValueInr: 4820000,
  },
  {
    id: "LR-100235",
    ownerName: "Sunita Devi",
    guardianName: "Sh. Mahavir Prasad",
    village: "Dadri",
    district: "Gautam Buddh Nagar",
    state: "Uttar Pradesh",
    khasraNumber: "88/1",
    khatauniNumber: "0542",
    areaValue: 0.8,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Pending",
    registrationDate: "2023-07-19",
    lastUpdated: "2026-09-01",
    documentName: "dadri-plot-88-1-photo.jpg",
    documentType: "Image",
    documentSizeKb: 1120,
    mutationNumber: "MUT-81904",
    marketValueInr: 3150000,
  },
  {
    id: "LR-100236",
    ownerName: "Iqbal Singh Gill",
    guardianName: "Sh. Harbhajan Singh Gill",
    village: "Bhucho Kalan",
    district: "Bathinda",
    state: "Punjab",
    khasraNumber: "215/4",
    khatauniNumber: "2201",
    areaValue: 6.2,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2015-11-02",
    lastUpdated: "2026-07-28",
    documentName: "gill-farmland-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 3040,
    mutationNumber: "MUT-64110",
    marketValueInr: 11400000,
  },
  {
    id: "LR-100237",
    ownerName: "Meena Kumari",
    guardianName: "Sh. Om Prakash",
    village: "Chomu",
    district: "Jaipur",
    state: "Rajasthan",
    khasraNumber: "56/3",
    khatauniNumber: "0987",
    areaValue: 1.1,
    areaUnit: "Bigha",
    landType: "Residential",
    status: "Under Review",
    registrationDate: "2024-01-14",
    lastUpdated: "2026-09-05",
    documentName: "chomu-plot-application.pdf",
    documentType: "PDF",
    documentSizeKb: 980,
    mutationNumber: "MUT-90233",
    marketValueInr: 1890000,
  },
  {
    id: "LR-100238",
    ownerName: "P. Lakshmi Narayanan",
    guardianName: "Sh. K. Narayanan",
    village: "Thiruporur",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    khasraNumber: "N/A",
    khatauniNumber: "S-2210",
    areaValue: 0.5,
    areaUnit: "Acres",
    landType: "Commercial",
    status: "Verified",
    registrationDate: "2018-06-23",
    lastUpdated: "2026-06-14",
    documentName: "thiruporur-shop-patta.pdf",
    documentType: "PDF",
    documentSizeKb: 1760,
    mutationNumber: "MUT-55871",
    marketValueInr: 6700000,
  },
  {
    id: "LR-100239",
    ownerName: "Arvind Bhoi",
    guardianName: "Sh. Chaitan Bhoi",
    village: "Khordha",
    district: "Khordha",
    state: "Odisha",
    khasraNumber: "302/1",
    khatauniNumber: "1445",
    areaValue: 3.6,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Pending",
    registrationDate: "2022-09-30",
    lastUpdated: "2026-08-20",
    documentName: "khordha-field-scan.jpg",
    documentType: "Image",
    documentSizeKb: 2050,
    mutationNumber: "MUT-73302",
    marketValueInr: 2980000,
  },
  {
    id: "LR-100240",
    ownerName: "Farida Bano",
    guardianName: "Sh. Aslam Sheikh",
    village: "Malegaon",
    district: "Nashik",
    state: "Maharashtra",
    khasraNumber: "141/2A",
    khatauniNumber: "0765",
    areaValue: 0.3,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Rejected",
    registrationDate: "2023-12-05",
    lastUpdated: "2026-08-11",
    documentName: "malegaon-141-2a-affidavit.pdf",
    documentType: "PDF",
    documentSizeKb: 640,
    mutationNumber: "MUT-88410",
    marketValueInr: 1420000,
  },
  {
    id: "LR-100241",
    ownerName: "Girish Hegde",
    guardianName: "Sh. Ramachandra Hegde",
    village: "Sirsi",
    district: "Uttara Kannada",
    state: "Karnataka",
    khasraNumber: "27/1B",
    khatauniNumber: "1120",
    areaValue: 4.8,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2016-04-17",
    lastUpdated: "2026-05-30",
    documentName: "hegde-plantation-record.pdf",
    documentType: "PDF",
    documentSizeKb: 2890,
    mutationNumber: "MUT-40987",
    marketValueInr: 8250000,
  },
  {
    id: "LR-100242",
    ownerName: "Deepak Barman",
    guardianName: "Sh. Nirmal Barman",
    village: "Sonapur",
    district: "Kamrup",
    state: "Assam",
    khasraNumber: "63/2",
    khatauniNumber: "0331",
    areaValue: 1.9,
    areaUnit: "Bigha",
    landType: "Agricultural",
    status: "Under Review",
    registrationDate: "2024-02-27",
    lastUpdated: "2026-09-08",
    documentName: "sonapur-jamabandi.pdf",
    documentType: "PDF",
    documentSizeKb: 1340,
    mutationNumber: "MUT-92117",
    marketValueInr: 1160000,
  },
  {
    id: "LR-100243",
    ownerName: "Harpreet Kaur Sandhu",
    guardianName: "Sh. Gurdev Singh Sandhu",
    village: "Zirakpur",
    district: "SAS Nagar",
    state: "Punjab",
    khasraNumber: "199/3",
    khatauniNumber: "1789",
    areaValue: 0.6,
    areaUnit: "Acres",
    landType: "Commercial",
    status: "Verified",
    registrationDate: "2020-10-09",
    lastUpdated: "2026-07-02",
    documentName: "zirakpur-commercial-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 2210,
    mutationNumber: "MUT-61455",
    marketValueInr: 15600000,
  },
  {
    id: "LR-100244",
    ownerName: "Chandrashekar Reddy",
    guardianName: "Sh. Venkat Reddy",
    village: "Shamshabad",
    district: "Rangareddy",
    state: "Telangana",
    khasraNumber: "N/A",
    khatauniNumber: "S-3301",
    areaValue: 2.2,
    areaUnit: "Acres",
    landType: "Barren",
    status: "Pending",
    registrationDate: "2023-03-21",
    lastUpdated: "2026-08-27",
    documentName: "shamshabad-land-photo.jpg",
    documentType: "Image",
    documentSizeKb: 1580,
    mutationNumber: "MUT-79004",
    marketValueInr: 5230000,
  },
  {
    id: "LR-100245",
    ownerName: "Anita Rani Sharma",
    guardianName: "Sh. Vijay Sharma",
    village: "Panipat",
    district: "Panipat",
    state: "Haryana",
    khasraNumber: "509/1",
    khatauniNumber: "2044",
    areaValue: 1.4,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Verified",
    registrationDate: "2017-08-30",
    lastUpdated: "2026-04-19",
    documentName: "panipat-509-1-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 1990,
    mutationNumber: "MUT-38221",
    marketValueInr: 4310000,
  },
  {
    id: "LR-100246",
    ownerName: "Bipin Chandra Joshi",
    guardianName: "Sh. Devi Prasad Joshi",
    village: "Almora",
    district: "Almora",
    state: "Uttarakhand",
    khasraNumber: "72/4",
    khatauniNumber: "0410",
    areaValue: 0.9,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Pending",
    registrationDate: "2022-05-16",
    lastUpdated: "2026-08-15",
    documentName: "almora-72-4-scan.jpg",
    documentType: "Image",
    documentSizeKb: 1440,
    mutationNumber: "MUT-70519",
    marketValueInr: 1750000,
  },
  {
    id: "LR-100247",
    ownerName: "Suresh Prajapati",
    guardianName: "Sh. Manilal Prajapati",
    village: "Anand",
    district: "Anand",
    state: "Gujarat",
    khasraNumber: "N/A",
    khatauniNumber: "S-1204",
    areaValue: 3.1,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2014-12-01",
    lastUpdated: "2026-03-22",
    documentName: "anand-farm-record.pdf",
    documentType: "PDF",
    documentSizeKb: 2670,
    mutationNumber: "MUT-29981",
    marketValueInr: 6980000,
  },
  {
    id: "LR-100248",
    ownerName: "Nazia Firdaus",
    guardianName: "Sh. Shakeel Ahmad",
    village: "Barabanki",
    district: "Barabanki",
    state: "Uttar Pradesh",
    khasraNumber: "134/2",
    khatauniNumber: "0688",
    areaValue: 0.4,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Under Review",
    registrationDate: "2024-06-08",
    lastUpdated: "2026-09-10",
    documentName: "barabanki-134-2-application.pdf",
    documentType: "PDF",
    documentSizeKb: 870,
    mutationNumber: "MUT-95530",
    marketValueInr: 980000,
  },
  {
    id: "LR-100249",
    ownerName: "Manohar Lal Meena",
    guardianName: "Sh. Shivraj Meena",
    village: "Sawai Madhopur",
    district: "Sawai Madhopur",
    state: "Rajasthan",
    khasraNumber: "18/1",
    khatauniNumber: "1502",
    areaValue: 5.5,
    areaUnit: "Bigha",
    landType: "Agricultural",
    status: "Rejected",
    registrationDate: "2023-10-13",
    lastUpdated: "2026-07-09",
    documentName: "sawai-madhopur-18-1-doc.pdf",
    documentType: "PDF",
    documentSizeKb: 1120,
    mutationNumber: "MUT-83017",
    marketValueInr: 2140000,
  },
  {
    id: "LR-100250",
    ownerName: "Vinod Kumar Thakur",
    guardianName: "Sh. Ramesh Thakur",
    village: "Solan",
    district: "Solan",
    state: "Himachal Pradesh",
    khasraNumber: "44/3",
    khatauniNumber: "0299",
    areaValue: 1.6,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Verified",
    registrationDate: "2019-09-25",
    lastUpdated: "2026-06-01",
    documentName: "solan-44-3-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 2010,
    mutationNumber: "MUT-51772",
    marketValueInr: 5680000,
  },
  {
    id: "LR-100251",
    ownerName: "Kavita Mondal",
    guardianName: "Sh. Ashok Mondal",
    village: "Bolpur",
    district: "Birbhum",
    state: "West Bengal",
    khasraNumber: "97/1",
    khatauniNumber: "0741",
    areaValue: 0.7,
    areaUnit: "Bigha",
    landType: "Agricultural",
    status: "Pending",
    registrationDate: "2023-01-29",
    lastUpdated: "2026-08-24",
    documentName: "bolpur-97-1-scan.jpg",
    documentType: "Image",
    documentSizeKb: 1290,
    mutationNumber: "MUT-84420",
    marketValueInr: 890000,
  },
  {
    id: "LR-100252",
    ownerName: "Rajendra Prasad Verma",
    guardianName: "Late Sh. Shyam Lal Verma",
    village: "Muzaffarpur",
    district: "Muzaffarpur",
    state: "Bihar",
    khasraNumber: "205/6",
    khatauniNumber: "1663",
    areaValue: 2.0,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2013-02-19",
    lastUpdated: "2026-02-27",
    documentName: "muzaffarpur-205-6-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 2450,
    mutationNumber: "MUT-19908",
    marketValueInr: 3620000,
  },
  {
    id: "LR-100253",
    ownerName: "Thomas P. Varghese",
    guardianName: "Sh. P. O. Varghese",
    village: "Kottayam",
    district: "Kottayam",
    state: "Kerala",
    khasraNumber: "N/A",
    khatauniNumber: "S-0871",
    areaValue: 0.45,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Verified",
    registrationDate: "2020-03-04",
    lastUpdated: "2026-05-11",
    documentName: "kottayam-property-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 1870,
    mutationNumber: "MUT-45391",
    marketValueInr: 4970000,
  },
  {
    id: "LR-100254",
    ownerName: "Sandeep Malviya",
    guardianName: "Sh. Rajesh Malviya",
    village: "Ratlam",
    district: "Ratlam",
    state: "Madhya Pradesh",
    khasraNumber: "310/2",
    khatauniNumber: "1029",
    areaValue: 3.3,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Under Review",
    registrationDate: "2024-04-02",
    lastUpdated: "2026-09-06",
    documentName: "ratlam-310-2-application.pdf",
    documentType: "PDF",
    documentSizeKb: 1105,
    mutationNumber: "MUT-96602",
    marketValueInr: 2870000,
  },
  {
    id: "LR-100255",
    ownerName: "Priyanka Dey",
    guardianName: "Sh. Subrata Dey",
    village: "Agartala",
    district: "West Tripura",
    state: "Tripura",
    khasraNumber: "58/1",
    khatauniNumber: "0455",
    areaValue: 0.35,
    areaUnit: "Acres",
    landType: "Residential",
    status: "Pending",
    registrationDate: "2023-11-17",
    lastUpdated: "2026-08-18",
    documentName: "agartala-58-1-photo.jpg",
    documentType: "Image",
    documentSizeKb: 950,
    mutationNumber: "MUT-85519",
    marketValueInr: 1240000,
  },
  {
    id: "LR-100256",
    ownerName: "Balbir Singh Chahal",
    guardianName: "Sh. Kartar Singh Chahal",
    village: "Moga",
    district: "Moga",
    state: "Punjab",
    khasraNumber: "76/5",
    khatauniNumber: "1830",
    areaValue: 7.0,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Verified",
    registrationDate: "2011-07-22",
    lastUpdated: "2026-01-30",
    documentName: "moga-76-5-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 3210,
    mutationNumber: "MUT-10442",
    marketValueInr: 12900000,
  },
  {
    id: "LR-100257",
    ownerName: "Ganesh Waghmare",
    guardianName: "Sh. Dattu Waghmare",
    village: "Latur",
    district: "Latur",
    state: "Maharashtra",
    khasraNumber: "231/1",
    khatauniNumber: "0899",
    areaValue: 1.75,
    areaUnit: "Acres",
    landType: "Agricultural",
    status: "Rejected",
    registrationDate: "2023-08-08",
    lastUpdated: "2026-07-15",
    documentName: "latur-231-1-doc.pdf",
    documentType: "PDF",
    documentSizeKb: 780,
    mutationNumber: "MUT-81225",
    marketValueInr: 2020000,
  },
  {
    id: "LR-100258",
    ownerName: "Neha Agarwal",
    guardianName: "Sh. Mukesh Agarwal",
    village: "Sonipat",
    district: "Sonipat",
    state: "Haryana",
    khasraNumber: "94/2",
    khatauniNumber: "0567",
    areaValue: 0.25,
    areaUnit: "Acres",
    landType: "Commercial",
    status: "Verified",
    registrationDate: "2021-05-27",
    lastUpdated: "2026-06-25",
    documentName: "sonipat-94-2-deed.pdf",
    documentType: "PDF",
    documentSizeKb: 1650,
    mutationNumber: "MUT-58873",
    marketValueInr: 7400000,
  },
];

export const recentUploads: RecentUpload[] = [
  {
    id: "UP-5231",
    fileName: "barabanki-134-2-application.pdf",
    relatedRecordId: "LR-100248",
    uploadedAt: "2026-09-10T09:42:00+05:30",
    sizeKb: 870,
    status: "Processed",
  },
  {
    id: "UP-5230",
    fileName: "ratlam-310-2-application.pdf",
    relatedRecordId: "LR-100254",
    uploadedAt: "2026-09-06T14:05:00+05:30",
    sizeKb: 1105,
    status: "Processed",
  },
  {
    id: "UP-5229",
    fileName: "sonapur-jamabandi.pdf",
    relatedRecordId: "LR-100242",
    uploadedAt: "2026-09-08T11:20:00+05:30",
    sizeKb: 1340,
    status: "Processing",
  },
  {
    id: "UP-5228",
    fileName: "chomu-plot-application.pdf",
    relatedRecordId: "LR-100237",
    uploadedAt: "2026-09-05T16:58:00+05:30",
    sizeKb: 980,
    status: "Processed",
  },
  {
    id: "UP-5227",
    fileName: "malegaon-141-2a-affidavit.pdf",
    relatedRecordId: "LR-100240",
    uploadedAt: "2026-08-11T10:12:00+05:30",
    sizeKb: 640,
    status: "Failed",
  },
];

export const indianStates: string[] = Array.from(
  new Set(landRecords.map((r) => r.state))
).sort();

export const districtsByState: Record<string, string[]> = landRecords.reduce(
  (acc, record) => {
    if (!acc[record.state]) acc[record.state] = [];
    if (!acc[record.state].includes(record.district)) {
      acc[record.state].push(record.district);
    }
    return acc;
  },
  {} as Record<string, string[]>
);
